ProjectManager/ProjectManager.MVCUI/Controllers/AdminManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize(Roles = "Admin")]//admin@gmail.com C@de1234
    public class AdminManagerController : Controller
    {
        // GET: AdminManager
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Controllers/DepartmentManagerController.cs
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize(Roles = "Admin")]//admin@gmail.com C@de1234
    public class DepartmentManagerController : Controller
    {
        private readonly IRepository<DepartmentModel> _departmentModelRepository;
        private readonly IRepository<EmployeeModel> _employeeModelRepository;
        public DepartmentManagerController(IRepository<DepartmentModel> departmentModelRepository, IRepository<EmployeeModel> employeeModelRepository)
        {
            _departmentModelRepository = departmentModelRepository;
            _employeeModelRepository = employeeModelRepository;
        }
        // GET: DepartmentManager
        public ActionResult Index()
        {
          List<DepartmentModel> departmentList = _departmentModelRepository.Collection().ToList();

            return View(departmentList);
        }
        public ActionResult DepartmentEmployees(int id)
        {
            DepartmentModel departmentModel = _departmentModelRepository.GetbyId(id);
            if (departmentModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                List<EmployeeModel> employeeList = _employeeModelRepository.Collection().Where(x => x.DepartmentId == departmentModel.Id).ToList();
                ViewBag.TotalEmployee = employeeList.Count();
                return View(employeeList);
            }
        }
        public ActionResult Create()
        {
            DepartmentModel departmentModel = new DepartmentModel();

            return View(departmentModel);
        }
        [HttpPost]
        public ActionResult Create(DepartmentModel departmentModel)
        {
            if (!ModelState.IsValid)
            {
                return View(departmentModel);
            }
            else
            {
                _departmentModelRepository.Insert(departmentModel);
                _departmentModelRepository.Commit();

                return RedirectToAction("Index");
            }
        }
        public ActionResult Edit(int Id)
        {
            DepartmentModel departmentModel = _departmentModelRepository.GetbyId(Id);
            if (departmentModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(departmentModel);
            }
        }
        [HttpPost]
        public ActionResult Edit(DepartmentModel departmentModel, int Id)
        {
            DepartmentModel departmentModelToUpdate = _departmentModelRepository.GetbyId(Id);
            if (departmentModelToUpdate == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(departmentModelToUpdate);
                }
                else
                {
                    departmentModelToUpdate.Name = departmentModel.Name;
                    _departmentModelRepository.Commit();

                    return RedirectToAction("Index");
                }
            }
        }
        public ActionResult Delete(int id)
        {
            DepartmentModel departmentModel = _departmentModelRepository.GetbyId(id);
            if (departmentModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(departmentModel);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            DepartmentModel departmentModelToDelete = _departmentModelRepository.GetbyId(id);
            if (departmentModelToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                _departmentModelRepository.Delete(id);
                _departmentModelRepository.Commit();

                return RedirectToAction("Index");
            }
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Views/DepartmentManager/Create.cshtml
@model ProjectManager.Core.Models.DepartmentModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a new department</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Admin Page", "Index", "AdminManager", null, new { @class = "btn btn-default" }) |
    @Html.ActionLink("Go to Department List", "Index",null,new {@class="btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectManager/ProjectManager.MVCUI/Views/DepartmentManager/Delete.cshtml
@model ProjectManager.Core.Models.DepartmentModel

@{
    ViewBag.Title = "Delete";
}

<br />

<h3>Are you sure you want to delete @Model.Name department?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">

        <dt>
           Department Name : 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
           Created Date : 
        </dt>

        <dd>
            @Model.CreatedAt.ToString("dd.MM.yyyy")
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to Department List", "Index",null,new {@class="btn btn-default" })
        </div>
    }
</div>

ProjectManager/ProjectManager.MVCUI/Views/DepartmentManager/DepartmentEmployees.cshtml
@model IEnumerable<ProjectManager.Core.Models.EmployeeModel>

@{
    ViewBag.Title = "DepartmentEmployees";
}
<br />
<p>
    @Html.ActionLink("Create New Employee", "Create","DepartmentManager",null,new {@class="btn btn-primary" }) | 
    @Html.ActionLink("Go back to departments", "Index", "DepartmentManager", null, new { @class = "btn btn-default" })

</p>
<br />
<hr />

<div class="row">
    <div class="col-lg-12">
    </div>
    @foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-4 col-xs-6 thumb"  style="border-color:blue;border:1px solid;margin:3px;padding:3px;box-shadow:1px 2px #A9A9A9">

            <a href="GalleryImages/GalleryManager">
                <img class="img-thumbnail center-block" src="~/Content/EmployeeImage/@item.Url" style="height:140px;width:50%">
            </a>
            <h4 class="text-center"><b>@item.FirstName.ToUpper() @item.LastName.ToUpper()</b></h4>
            <ul style="list-style:none;text-align:left">
                <li><b>Gender : </b>@(item.Gender==true?"Male":"Female")</li>
                <li><b>Age : </b> @(DateTime.Now.Year-@item.DateOfBirth.Year)</li>
                <li><b>Start Date : </b>@item.CreatedAt.ToString("dd.MM.yyyy")</li>

            </ul>

        </div>


    }
</div>

ProjectManager/ProjectManager.MVCUI/Views/DepartmentManager/Edit.cshtml
@model ProjectManager.Core.Models.DepartmentModel

@{
    ViewBag.Title = "Edit";
}
<br />
<h2>Edit @Model.Name Department</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                @Html.ActionLink("Back to Department List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectManager/ProjectManager.MVCUI/Views/DepartmentManager/Index.cshtml
@model IEnumerable<ProjectManager.Core.Models.DepartmentModel>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>

<html>
<head>
    <title>Departments</title>

    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <hr /><br /><br />
    <p>
        @Html.ActionLink("Create a New Department", "Create", null, new { @class = "btn btn-primary" }) |
        @Html.ActionLink("Back to Admin Page", "Index", "AdminManager", null, new { @class = "btn btn-default" })
    </p>
    <br />
    <table id="departmentDatatable" class="table table-bordered">
        <thead>
            <tr>
                <th>
                    Department Name
                </th>
                <th>
                    Created at
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @item.CreatedAt.ToString("dd.MM.yyyy")
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure to Delete?')" })
                    </td>
                    <td>
                        <a href="@Url.Action("DepartmentEmployees","DepartmentManager",new {id=item.Id })" class="btn btn-primary">
                            See Employees
                        </a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap.min.js"></script>
</body>
</html>

<script>
    $(document).ready(function () {
        $('#departmentDatatable').DataTable();
    });
</script>