ProjectManager/ProjectManager.MVCUI/Controllers/GalleryManagerController.cs
using Microsoft.AspNet.Identity;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.DynamicData;
using System.Web.Mvc;
using WebGrease.Activities;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize]
    public class GalleryManagerController : Controller
    {
        private readonly IRepository<GalleryModel> _galleryModelRepository;
        private readonly IRepository<GalleryImageModel> _galleryImageRepository;
        public GalleryManagerController(IRepository<GalleryModel> galleryModelRepository, IRepository<GalleryImageModel> galleryImageRepository)
        {
            _galleryModelRepository = galleryModelRepository;
            _galleryImageRepository = galleryImageRepository;
        }
        public ActionResult Index()
        {
            string loggedInUserId = User.Identity.GetUserId();
            List<GalleryModel> galleryModels = _galleryModelRepository.Collection().Where(x => x.ManagerModelId == loggedInUserId).ToList();
            ViewBag.PhotoCount = galleryModels.Count;

            return View(galleryModels);
        }
        public ActionResult GalleryImages(int id)
        {
            GalleryModel model = _galleryModelRepository.GetbyId(id);

            if (model == null)
            {
                return HttpNotFound();
            }
            else
            {
                List<GalleryImageModel> listOfImages = _galleryImageRepository.Collection().Where(x => x.GalleryModelId == model.Id).ToList();
                ViewBag.Photos = listOfImages.Count;
                return View(listOfImages);
            }
        }
        public ActionResult Create()
        {
            GalleryModel galleryModel = new GalleryModel();

            return View(galleryModel);
        }
        [HttpPost]
        public ActionResult Create(GalleryModel galleryModel, HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(galleryModel);
            }
            else
            {
                if (file != null)
                {
                    string loggedInuserId = User.Identity.GetUserId();
                    galleryModel.ManagerModelId = loggedInuserId;
                    galleryModel.Url = galleryModel.Id + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//Galleries//") + galleryModel.Url);
                }
                _galleryModelRepository.Insert(galleryModel);
                _galleryModelRepository.Commit();
                ModelState.Clear();
                return RedirectToAction("Index");
            }
        }
        public ActionResult Edit(int id)
        {
            GalleryModel galleryModel = _galleryModelRepository.GetbyId(id);
            if (galleryModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(galleryModel);
            }
        }
        [HttpPost]
        public ActionResult Edit(GalleryModel galleryModel, int id, HttpPostedFileBase file)
        {
            GalleryModel galleryModelToDelete = _galleryModelRepository.GetbyId(id);
            if (galleryModelToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(galleryModelToDelete);
                }
                else
                {
                    if (file != null)
                    {
                        galleryModelToDelete.Url = galleryModel.Id + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                        file.SaveAs(Server.MapPath("//Content//Galleries//") + galleryModelToDelete.Url);
                    }
                    galleryModelToDelete.Title = galleryModel.Title;

                    _galleryModelRepository.Commit();

                    return RedirectToAction("Index");
                }
            }

        }
        public ActionResult Delete(int id)
        {
            GalleryModel galleryModel = _galleryModelRepository.GetbyId(id);
            if (galleryModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(galleryModel);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            GalleryModel galleryModelToDelete = _galleryModelRepository.GetbyId(id);
            if (galleryModelToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                _galleryModelRepository.Delete(id);
                _galleryModelRepository.Commit();

                return RedirectToAction("Index");
            }
        }

    }
}

ProjectManager/ProjectManager.MVCUI/Controllers/HomeController.cs
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManager.MVCUI.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly IRepository<GalleryModel> _galleryRepository;
        public HomeController(IRepository<GalleryModel> galleryRepository)
        {
            _galleryRepository = galleryRepository;
        }
        public ActionResult Index()
        {
            List<GalleryModel> galleryList = _galleryRepository.Collection().OrderBy(x => x.CreatedAt).ToList();
          
            foreach (var item in galleryList)
            {
                DateTime today = DateTime.Now;
                DateTime createdDate = item.CreatedAt;
                TimeSpan timeSpan = today.Subtract(createdDate);

                if (timeSpan.TotalDays <1)
                {
                    ViewBag.CreatedAt = "Created Today";
                }
                else if (timeSpan.TotalDays==1)
                {
                    ViewBag.CreatedAt = "Created Yesterday";
                }
                else
                {
                    ViewBag.CreatedAt =timeSpan.TotalDays + " Days Ago Created";
                }
            }

            return View(galleryList);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProjectManager/ProjectManager.MVCUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjectManager/ProjectManager.MVCUI/Views/Home/Index.cshtml
@model IEnumerable<ProjectManager.Core.Models.GalleryModel>
@{
    ViewBag.Title = "Home Page";
}
<br />
<hr />
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <style>
        .Title {
            color: white;
            background-color: #001f3f;
            border: 1px solid #0275d8;
            padding: 12px;
            margin: 1px;
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="col-md-3">
            <div class="col-md-12">
                <a href="@Url.Action("Create", "GalleryManager")" class="btn btn-default btn-lg" style="color:#0275d8;box-shadow: 1px 2px #0275d8">
                    <span class="glyphicon glyphicon-plus"></span> Create Your Gallery
                </a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="col-md-12">
                <!--Test-->
                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>
                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox" >
                        @{ int i = 0;}
                        @foreach (var item in Model)
                        {
                            i++;
                            var activeImage = i == 1 ? "active" : "";
                            <div class="item @activeImage">
                                <h4 class="Title">@item.Title Gallery</h4>
                                <img class="img-thumbnail" src="~/Content/Galleries/@item.Url" style="height:550px;width:100%" alt="@item.Title">
                                <p class="Title">@ViewBag.CreatedAt</p>
                            </div>
                        }
                    </div>
                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>

</body>
</html>