ProjectManager/ProjectManager.MVCUI/Controllers/AdminManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize(Roles = "Admin")]//admin@gmail.com C@de1234
    public class AdminManagerController : Controller
    {
        // GET: AdminManager
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Controllers/EmployeeManagerController.cs
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ProjectManager.Core.ViewModels;
using System.IO;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize(Roles = "Admin")]//admin@gmail.com C@de1234
    public class EmployeeManagerController : Controller
    {
        private readonly IRepository<EmployeeModel> _employeeRepository;
        private readonly IRepository<DepartmentModel> _departmentRepository;
        public EmployeeManagerController(IRepository<EmployeeModel> employeeRepository, IRepository<DepartmentModel> departmentRepository)
        {
            _employeeRepository = employeeRepository;
            _departmentRepository = departmentRepository;
        }
        public ActionResult Index()
        {
            List<EmployeeModel> employeeModel = _employeeRepository.Collection().Include(x=>x.DepartmentModel).ToList();
            return View(employeeModel);
        }
        public ActionResult Create()
        {
            EmployeeViewModel employeeModel = new EmployeeViewModel()
            {
                EmployeeModel = new EmployeeModel(),
                DepartmentModels = _departmentRepository.Collection()
            };

            return View(employeeModel);
        }
        [HttpPost]
        public ActionResult Create(EmployeeModel employeeModel,HttpPostedFileBase file)
        {
            if (!ModelState.IsValid)
            {
                return View(employeeModel);
            }
            else
            {
                if (file!=null)
                {
                    employeeModel.Url = employeeModel.Id + Path.GetFileNameWithoutExtension(file.FileName)+".jpg";
                    file.SaveAs(Server.MapPath("//Content//EmployeeImage//") + employeeModel.Url);
                }
                _employeeRepository.Insert(employeeModel);
                _employeeRepository.Commit();

                return RedirectToAction("Index");
            }
        }
        public ActionResult Edit(EmployeeModel employeeModel,int id,HttpPostedFileBase file)
        {
            EmployeeModel employeeModelToEdit = _employeeRepository.GetbyId(id);
            if (employeeModelToEdit==null)
            {
                return HttpNotFound();
            }
            else
            {
                EmployeeViewModel employeeViewModel = new EmployeeViewModel()
                {
                    EmployeeModel = employeeModelToEdit,
                    DepartmentModels = _departmentRepository.Collection()
                };
                return View(employeeViewModel);
            }
        }
        [HttpPost]
        public ActionResult Edit(int id,EmployeeModel employeeModel,HttpPostedFileBase file)
        {
            EmployeeModel employeeModelToEdit = _employeeRepository.GetbyId(id);
            if (employeeModelToEdit==null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(employeeModelToEdit);
                }
                else
                {
                    if (file!=null)
                    {
                        employeeModelToEdit.Url = employeeModel.Id + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                        file.SaveAs(Server.MapPath("//Content//EmployeeImage//") + employeeModelToEdit.Url);
                    }
                    employeeModelToEdit.FirstName = employeeModel.FirstName;
                    employeeModelToEdit.LastName = employeeModel.LastName;
                    employeeModelToEdit.Gender = employeeModel.Gender;
                    employeeModelToEdit.EMail = employeeModel.EMail;
                    employeeModelToEdit.DateOfBirth = employeeModel.DateOfBirth;
                    employeeModelToEdit.DepartmentId = employeeModel.DepartmentId;

                    _employeeRepository.Commit();

                    return RedirectToAction("Index");
                }
            }
        }
        public ActionResult Delete(int id)
        {
            EmployeeModel employeeModel = _employeeRepository.GetbyId(id);
            if (employeeModel==null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(employeeModel);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            EmployeeModel employeeModelToDelete = _employeeRepository.GetbyId(id);
            if (employeeModelToDelete==null)
            {
                return HttpNotFound();
            }
            else
            {
                _employeeRepository.Delete(id);
                _employeeRepository.Commit();

                return RedirectToAction("Index");
            }
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Views/EmployeeManager/Create.cshtml
@model ProjectManager.Core.ViewModels.EmployeeViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a new employee</h2>


@using (Html.BeginForm("Create", "EmployeeManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="col-md-3">
        <div class="form-group">
            <div class="text-center">
                <h4>Upload an Employee Image</h4>
            </div>
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeModel.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeModel.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.DateOfBirth,"{0:yyyy-MM-dd}",new { htmlAttributes = new { @class = "form-control",type="date"} })
               
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="radio">
                    <label>
                        @Html.RadioButtonFor(model => model.EmployeeModel.Gender, true) Male
                    </label>
                    <label>
                        @Html.RadioButtonFor(model => model.EmployeeModel.Gender, false) Female
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeModel.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EmployeeModel.DepartmentId, new SelectList(Model.DepartmentModels, "Id", "Name"), "Choose a Department", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>

    </div>
</div>
}

<div>
   @Html.ActionLink("Back to Admin Page","Index","AdminManager",null,new {@class="btn btn-default" }) |
    @Html.ActionLink("Go to Employee List", "Index",null,new {@class="btn btn-default" }) 
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectManager/ProjectManager.MVCUI/Views/EmployeeManager/Delete.cshtml
@model ProjectManager.Core.Models.EmployeeModel

@{
    ViewBag.Title = "Delete";
}
    <br />

<h3>Are you sure you want to delete @Model.FirstName.ToUpper() @Model.LastName.ToUpper()?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>

        </dt>

        <dd>
            <img class="img-responsive" style="height:200px;box-shadow:2px 4px #A9A9A9" src="~/Content/EmployeeImage/@Model.Url" />
        </dd>
        <br />
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @(Model.Gender==true?"Male":"Female")
        </dd>
        
        <dt>
          Age
        </dt>

        <dd>
           @(DateTime.Now.Year-Model.DateOfBirth.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <hr />
      <dt></dt>

      <dd>
          @using (Html.BeginForm())
          {
              @Html.AntiForgeryToken()

              <div class="form-actions no-color">
                  <input type="submit" value="Delete" class="btn btn-danger" /> |
                  @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
              </div>
          }
      </dd>
    </dl>
</div>

ProjectManager/ProjectManager.MVCUI/Views/EmployeeManager/Edit.cshtml
@model ProjectManager.Core.ViewModels.EmployeeViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Model.EmployeeModel.FirstName.ToUpper() @Model.EmployeeModel.LastName.ToUpper()</h2>
<img class="img-responsive" style="height:80px;box-shadow:2px 4px #A9A9A9" src="~/Content/EmployeeImage/@Model.EmployeeModel.Url" />


@using (Html.BeginForm("Edit", "EmployeeManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.EmployeeModel.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeModel.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeModel.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.EmployeeModel.DateOfBirth, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="radio">
                    <label>
                        @Html.RadioButtonFor(model => model.EmployeeModel.Gender, true) Male
                    </label>
                    <label>
                        @Html.RadioButtonFor(model => model.EmployeeModel.Gender, false) Female
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="file" id="file" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeModel.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeModel.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeModel.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EmployeeModel.DepartmentId, new SelectList(Model.DepartmentModels, "Id", "Name"), "Choose a department", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectManager/ProjectManager.MVCUI/Views/EmployeeManager/Index.cshtml
@model IEnumerable<ProjectManager.Core.Models.EmployeeModel>

@{
    ViewBag.Title = "Index";
}
<br />

<h2>Employee List</h2>

<p>
    @Html.ActionLink("Create a New Employee", "Create", null, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to Admin Page", "Index", "AdminManager", null, new { @class = "btn btn-default" })
</p>
<hr />

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail"style="box-shadow:2px 4px #A9A9A9">

                <img class="img-thumbnail" style="height:150px;align-items:center;border-color:black;padding:5px" src="~/Content/EmployeeImage/@item.Url" />
                <div class="caption">
                    <h3 style="text-align:center;color:blue">@item.FirstName.ToUpper() @item.LastName.ToUpper()</h3>
                    <ul style="list-style:none">
                        <li><b>Age :</b> @(DateTime.Now.Year-item.DateOfBirth.Year)</li>
                        <li><b>Gender :</b> @(item.Gender==true?"Male":"Female")</li>
                        <li><b>E-mail :</b> @item.EMail</li>
                        <li><b>Department Name : </b>@item.DepartmentModel.Name</li>
                        <li><b>Start Date :</b> @item.CreatedAt.ToString("dd.MM.yyyy")</li>
                        <br />
                        <li>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default" }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                        </li>
                    </ul>

                </div>
            </div>

        </div>
    }

</div>