ProjectManager/ProjectManager.MVCUI/Controllers/AdminManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize(Roles = "Admin")]//admin@gmail.com C@de1234
    public class AdminManagerController : Controller
    {
        // GET: AdminManager
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Controllers/GalleryImageController.cs
using Microsoft.AspNet.Identity;
using ProjectManager.Core.Contracts;
using ProjectManager.Core.Models;
using ProjectManager.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManager.MVCUI.Controllers
{
    [Authorize]
    public class GalleryImageController : Controller
    {
        private readonly IRepository<GalleryImageModel> _galleryImageRepository;
        private readonly IRepository<GalleryModel> _galleryRepository;
        public GalleryImageController(IRepository<GalleryImageModel> galleryImageRepository, IRepository<GalleryModel> galleryRepository)
        {
            _galleryImageRepository = galleryImageRepository;
            _galleryRepository = galleryRepository;
        }
        public ActionResult Index()
        {

            string loggedInUserId = User.Identity.GetUserId();
            List<GalleryImageModel> imageList = _galleryImageRepository.Collection().Where(x => x.ManagerModelId == loggedInUserId).ToList();
            ViewBag.PhotoCount = imageList.Count;
            return View(imageList);
        }
        public ActionResult Create()
        {
            string loggedInUserGallery = User.Identity.GetUserId();
            GalleryImageViewModel galleryImageViewModel = new GalleryImageViewModel()
            {
               
                GalleryImageModel = new GalleryImageModel(),
                GalleryModels = _galleryRepository.Collection().Where(x=>x.ManagerModelId==loggedInUserGallery).ToList()
            };
            return View(galleryImageViewModel);
        }
        [HttpPost]
        public ActionResult Create(GalleryImageModel galleryImageModel, HttpPostedFileBase file)
        {
            MessageViewModel viewModel = new MessageViewModel();

            if (!ModelState.IsValid)
            {
                viewModel.Message = "An Error Occured";
                viewModel.Status = false;
                return View(galleryImageModel);
            }
           
            else
            {
               
                if (file != null)
                {
                    string LoggedInUserId = User.Identity.GetUserId();
                    galleryImageModel.ManagerModelId = LoggedInUserId;

                    galleryImageModel.Url = galleryImageModel.Id + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//GalleryImages//") + galleryImageModel.Url);
                    
                }
                _galleryImageRepository.Insert(galleryImageModel);
                viewModel.Message = "Added Successfully";

                _galleryImageRepository.Commit();
                viewModel.Status = true;
                viewModel.LinkText = "Back to Gallery";
                viewModel.Url = "/GalleryManager/Index";

                return View("_Message",viewModel);
            }
        }
        public ActionResult Edit(int id)
        {
            GalleryImageModel galleryImageModel = _galleryImageRepository.GetbyId(id);
            if (galleryImageModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                string loggedInUserGallery = User.Identity.GetUserId();
                GalleryImageViewModel galleryImageViewModel = new GalleryImageViewModel()
                {
                    GalleryImageModel = galleryImageModel,
                    GalleryModels = _galleryRepository.Collection().Where(x=>x.ManagerModelId==loggedInUserGallery).ToList()
                };
                return View(galleryImageViewModel);
            }
        }
        [HttpPost]
        public ActionResult Edit(int id, GalleryImageModel galleryImageModel, HttpPostedFileBase file)
        {
            GalleryImageModel galleryImageModelToEdit = _galleryImageRepository.GetbyId(id);
            if (galleryImageModelToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                MessageViewModel viewModel = new MessageViewModel();//Ajax begin form used

                if (!ModelState.IsValid)
                {
                    viewModel.Message = "An Error Occured";
                    viewModel.Status = false;
                    return View(galleryImageModelToEdit);
                   
                }
                if (file != null)
                {
                    galleryImageModelToEdit.Url = galleryImageModel.Id + Path.GetFileNameWithoutExtension(file.FileName) + ".jpg";
                    file.SaveAs(Server.MapPath("//Content//GalleryImages//") + galleryImageModelToEdit.Url);
                }
                galleryImageModelToEdit.Description = galleryImageModel.Description;
                galleryImageModelToEdit.GalleryModelId = galleryImageModel.GalleryModelId;

                viewModel.Message = "Updated Successfully";//Ajax begin form used

                _galleryImageRepository.Commit();

                viewModel.Status = true;
                viewModel.LinkText = "Back to Gallery";
                viewModel.Url = "/GalleryManager/Index";

                return View("_Message",viewModel);
            }
        }
        public ActionResult Delete(int id)
        {
            GalleryImageModel galleryImageModel = _galleryImageRepository.GetbyId(id);
            if (galleryImageModel == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(galleryImageModel);
            }
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult ConfirmDelete(int id)
        {
            GalleryImageModel galleryImageModelToDelete = _galleryImageRepository.GetbyId(id);
            if (galleryImageModelToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                _galleryImageRepository.Delete(id);
                _galleryImageRepository.Commit();

                return RedirectToAction("Index","GalleryManager");
            }
        }
    }
}

ProjectManager/ProjectManager.MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Human Resources</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-brand navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <p style="color:white;text-shadow:0.2px 0.2px white">
                    @Html.ActionLink("Human Resources", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </p>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "AdminManager")</li>
                    }
                    <li>@Html.ActionLink("Galleries", "Index", "GalleryManager")</li>
                    @*<li>@Html.ActionLink("Images", "Index", "GalleryImage")</li>*@
                </ul>

                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectManager/ProjectManager.MVCUI/Views/Shared/_Message.cshtml
@model ProjectManager.Core.ViewModels.MessageViewModel
    <br />
@if (Model.Status)
{
    <div class="alert alert-success" role="alert">
        @Model.Message <a href="@Model.Url">@Model.LinkText</a>
    </div>
}
else
{

    <div class="alert alert-danger" role="alert">
        @Model.Message <a href="@Model.Url">@Model.LinkText</a>
    </div>
}